### ISSUE TITLE
Add cli option to specify kind cluster name

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/RSI#16]
Allow me to override the kind cluster name value from the default `rasa`. This would be nice if I want to setup multiple clusters.

**Comment by tczekajlo** [comment]
> Allow me to override the kind cluster name value from the default `rasa`. This would be nice if I want to setup multiple clusters.

@rgstephens out of curiosity, would you like to setup multiple clusters to have multiple Rasa X deployments, or is there another reason behind it?

**Comment by rgstephens** [comment]
Yes, for test purposes, would like to have multiple clusters with different setups.

**Comment by tczekajlo** [comment]
> Yes, for test purposes, would like to have multiple clusters with different setups.

@rgstephens Actually, it'll be possible with `rasactl` - https://github.com/RasaHQ/rasactl/tree/init

**Comment by RASADSA** [comment]
@rgstephens REI will not include this feature. 
Either use rasactl or directly invoke KIND with your own configuration and use rasactl
