### ISSUE TITLE
Define explicitly context for kubectl

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/RSI#21]
To make sure that `kubectl` uses always the right context we should define it explicitly for all `kubectl` command execution.

**Comment by RASADSA** [comment]
When KIND was already running and installed no context was selected.
was fixed yesterday
https://github.com/RasaHQ/RSI/blob/3c52f4ecffe6f5f10efbc395d1c76f430e0677ab/rsi.sh#L513
this also happens only when you switch context in between script runs - but yeah it can happen.
